### ISSUE TITLE
tinycbor does not link on Windows 7 using MinGW.org GCC-6.3.0-1

### ISSUE THREAD

**Issue by telkamp** [intel/tinycbor#102]
Building tinycbor on my Windows 7 machine using MinGW GCC-6.3.0-1 (g++ compiler) caused a linker error:
lib/tinycbor/libtinycbor.a(cborencoder.c.obj): In function create_container:
cborencoder.c:460: undefined reference to static_assert
cborencoder.c:461: undefined reference to static_assert
collect2.exe: error: ld returned 1 exit status

It seems to me that your #if term in compilersupport_p.h(53) is not working in my case:
`#if __STDC_VERSION__ >= 201112L || __cplusplus >= 201103L || __cpp_static_assert >= 200410`
`#  define cbor_static_assert(x)         static_assert(x, #x)`
`#elif !defined(__cplusplus) && defined(__GNUC__) && (__GNUC__ * 100 + __GNUC_MINOR__ >= 406) && (__STDC_VERSION__ > 199901L)`
`#  define cbor_static_assert(x)         _Static_assert(x, #x)`
`#else`
`#  define cbor_static_assert(x)         ((void)sizeof(char[2*!!(x) - 1]))`
`#endif`

The first term `__STDC_VERSION__ >= 201112L` is true in my case, but I don't have the static_assert.
Can the first term be removed?
Otherwise: I found a quite similar term used in the RapidJSON library:
https://github.com/Tencent/rapidjson/blob/a7f687fdf812b9f9c7bf7f78eeb1261642f31623/include/rapidjson/rapidjson.h#L419
`#if __cplusplus >= 201103L || ( defined(_MSC_VER) && _MSC_VER >= 1800 )`
`#define RAPIDJSON_STATIC_ASSERT(x) \`
`   static_assert(x, RAPIDJSON_STRINGIFY(x))`
`#endif // C++11`
This might be an alternative.

**Comment by thiagomacieira** [comment]
If {{__STDC_VERSION__}} is 201112 and static_assert is failing, your compiler is broken.

Check if assert.h has a macro definition for {{static_assert}}. That's probably the issue. Please report upstream. Meanwhile, compile TinyCBOR in C99 mode (which is the default).

**Comment by thiagomacieira** [comment]
I doubt this is a TinyCBOR bug.

**Comment by telkamp** [comment]
My include/assert.h does not include a static_assert macro
I've re-installed MinGW completely, but this does not help. Compiler version is still mingw32-gcc-g++.
And I have to note that the compiler is invoked using the -std=c11 flag.

Instead, I have a _Static_assert...
I can not say if this is a MinGW issue. It seems that MinGW needs at least an extra #if to be able to compile tinycbor.

**Comment by thiagomacieira** [comment]
> My include/assert.h does not include a static_assert macro

and

> And I have to note that the compiler is invoked using the -std=c11 flag.

Those are the two problems. You need to fix at least one of them. The C11 standard says in chapter 7.2 "Diagnostics <assert.h>", paragraph 3:

> The macro
> ```
>     static_assert
> ```
> expands to `_Static_assert`

If you choose to compile in C11 mode, make sure your headers are correct. Otherwise, compile in C99 mode, which is the default.

I will accept a pull request that makes it possible to compile TinyCBOR in C11 with broken headers, but I won't make one myself.

**Comment by telkamp** [comment]
Yes, `static_assert` should have be expanded to `_Static_assert` following the C11 standard. I'm compiling tinycbor using -the std-c11 flag, but this does not force gcc to use the C11's version of assert.h.
But you can find discussions on stackoverflow.com where people report that not all C11 comilers support that macro, e.g. [https://stackoverflow.com/questions/30266009/availability-of-static-assert-c11](https://stackoverflow.com/questions/30266009/availability-of-static-assert-c11)

A quite simple solution might be to swap the first two #if checks, so we use _Static_assert when we know that we don't have c++, but our GCC is new enough:
`#if !defined(__cplusplus) && defined(__GNUC__) && (__GNUC__ * 100 + __GNUC_MINOR__ >= 406) && (__STDC_VERSION__ > 199901L)`
`#  define cbor_static_assert(x)         _Static_assert(x, #x)`
`#elif __STDC_VERSION__ >= 201112L || __cplusplus >= 201103L || __cpp_static_assert >= 200410`
`#  define cbor_static_assert(x)         static_assert(x, #x)`
`...`
This works for me and it has only a minimal impact to other configurations.
What do you think?

**Comment by thiagomacieira** [comment]
I don't want a check for GCC version. Like you said, the header comes from libc, not GCC.

You can also check if a macro is defined using #ifdef...

**Comment by thiagomacieira** [comment]
In any case, please report this issue to your libc. They **need** to update to add the necessary macros.

**Comment by telkamp** [comment]
The check for GCC **is** already in your code - I've only swapped the #ifdef statements, nothing else!
The `static_assert` issue is known by the glibc project. I don't know why they do not fix it.

**Comment by telkamp** [comment]
But ok, we should wait if there are more users reporting this problem,
For the meantime, I can live with it and I will swap the two `#ifdef` statements after checkout.

**Comment by erichkeane** [comment]
I think Thiago is recommending something closer to:

  #if (__STDC_VERSION__ >= 201112L || __cplusplus >= 201103L || __cpp_static_assert >= 200410) && defined(static_assert)

**Comment by erichkeane** [comment]
Actually...:

#if (__STDC_VERSION__ >= 201112L && defined(static_assert)) || __cplusplus >= 201103L || __cpp_static_assert >= 200410

**Comment by thiagomacieira** [comment]
Right, that's probably the magic incantation.

`static_assert` is a macro in C11 but is a keyword in C++11. It's UB to #define a keyword in C++, so an #if for it is not acceptable. Looks like I did something similar for Qt recently, see https://github.com/qt/qtbase/commit/0ac2dca977ecc4020f51af57908a2640d00bcd9e

**Comment by thiagomacieira** [comment]
> The static_assert issue is known by the glibc project. I don't know why they do not fix it.

They did, over 6 years ago. First appearing in glibc 2.16.

But that's not relevant, since you're not using glibc on MinGW. MinGW uses a separate libc and the issue must be reported there. They probably didn't know they had to do this. I had to supply a fix for @zephyrproject.
