### ISSUE TITLE
cbor_value_calculate_string_length() returns CborErrorUnexpectedEOF for non-chunked string

### ISSUE THREAD

**Issue by telkamp** [intel/tinycbor#104]
- I initialize a buffer with a single CBOR value (tstr "Hello" = h'65 48  65 6c 6c 6f' )
- then I initialize the parser using `cbor_parser_init(buffer, 6, 0, &m_parser, &m_it);`
- I assure that there is a tstr following using the function `cbor_value_is_text_string(&m_it)`
- when I read the tstr length using `cbor_value_calculate_string_length(&m_it, &buflen)`, a CborErrorUnexpectedEOF is returned. The tstr length stored in &buflen is invalid. I would not expect an error here.
- when I read the string length using `cbor_value_get_string_length(&m_it, &buflen)`, everything works as expected
Following the Api documentation, `cbor_value_calculate_string_length` should work for chunked strings and for non-chunked strings as well

**Comment by thiagomacieira** [comment]
Working theory: when `iterate_string_chunks` is called for the second time on the non-chunked string, it does:

```c
last_chunk:
        *bufferptr = NULL;
        *len = 0;
        return preparse_next_value(it);
```

That `preparse_next_value` will fail.

Let me write a unit test and debug this.

**Comment by thiagomacieira** [comment]
Sorry, that's exactly unit test `tst_Parser::stringLength` with data row `textstring5`. I cannot reproduce the issue.

Can you provide a full testcase?

**Comment by telkamp** [comment]
Sorry from my side: While extracting the testcase from my code, I noticed that I've done something that seems to be not supported by your tinycbor library. So it was my fault.
FYI: I have to parse an unenclosed list of single Cbor elements, lets say "Hello", "World", "...". I do not know how many single cbor elements are in my buffer, nor the single elements are part of an array.
To handle this, I've set the number of remaining elements m_it to 100:
`m_it.remaining = 100;`
So when trying to calculate the length of a single string in the buffer, the pointer reaches the end of the buffer, but `remaining` is still >0. This will give the `CborErrorUnexpectedEOF` error.
Below you find my test code.

I understand that manipulating `m_it` seems not to be an adequate solution. An option might be to initialize a new parser for every single element (`cbor_parser_init`). Do you know a better solution?

    const uint8_t buffer[6] = {0x65, 0x48, 0x65, 0x6C, 0x6C, 0x6F}; //"Hello"
    CborParser m_parser;
    CborValue m_it;
    CborError err;

    cbor_parser_init(buffer, sizeof(buffer), 0, &m_parser, &m_it);
    m_it.remaining = 2; // Dirty workaround!
    
    if (!cbor_value_at_end(&m_it)) {
        size_t tstrlen1;
        printf("is_text_string: %s\n", cbor_value_is_text_string(&m_it)?"true":"false");
        err = cbor_value_calculate_string_length(&m_it, &tstrlen1);
        printf("calculate_string_length: %d, err: %d\n", tstrlen1, err);
        char* tstr1 = new char[tstrlen1];
        err = cbor_value_copy_text_string(&m_it, tstr1, &tstrlen1, &m_it);
        printf("copy_text_string: %s, len: %d, err: %d\n", tstr1, tstrlen1, err);
    }

**Comment by thiagomacieira** [comment]
You can parse exactly one top-level element in the buffer provided to `cbor_parser_init`. In case you may have more data in your buffer after the end of the element, you can use `cbor_parser_get_next_byte` to get a pointer to it, after you've finished parsing. This way, you could read an unlimited quantity of single-element streams.

If you want to use the API, I'd recommend prepending a marker for array without length (0x9f) and then recursing into that element. But without the Break marker, you'll only find out that you've reached the end  by getting a `CborErroUnexpectedEOF` error.
