### ISSUE TITLE
encoder test

### ISSUE THREAD

**Issue by TaniaMirzin** [intel/tinycbor#107]
Hi , 
am using Ubuntu 14.04 
and 
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
For some reason encoder test fails with this:
______________________________________________________
tst_Encoder::arraysAndMaps() Received signal 11
FAIL!  : tst_Encoder::arraysAndMaps() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 69 passed, 1 failed, 0 skipped
********* Finished testing of tst_Encoder *********
Aborted
__________________________________________________________
It happens when addArraysAndMaps calls to   QTest::newRow("emptymap") << raw("\xa0") << make_map({ });
and the make_map function fails on auto m = Map(list);

What can be a reason for this?
Should I use a specific qt version to avoid this?
Thank you very much.

**Comment by thiagomacieira** [comment]
Qt 5.2.1 is too old. Please use at least 5.6. The tests are run against 5.9, using package qt59base from PPA "beineri/opt-qt593-trusty" (I guess I need to upgrade to 5.9.4)
