### ISSUE TITLE
online docs out of date

### ISSUE THREAD

**Issue by Smattr** [intel/tinycbor#119]
I think the docs available at https://intel.github.io/tinycbor/current/ need to be resynced from the source. I ran into an issue where the [decoding example code](https://intel.github.io/tinycbor/current/a00088.html#details) is incorrect. The comment responsible for the Doxygen output was fixed in f5a172b976de07f7bb37d2d24149d6c7a1e512e1, but it seems like this has not yet flowed through to the io pages.

**Comment by thiagomacieira** [comment]
I thought I'd updated it when I made the 0.5 release. Taking a look...

**Comment by thiagomacieira** [comment]
Ah, those changes were after the 0.5 release. Updating docs now then.

**Comment by Smattr** [comment]
Thanks, looks good now!
