### ISSUE TITLE
buffer bounds check error in get_utf8 function

### ISSUE THREAD

**Issue by phirsov** [intel/tinycbor#137]
Consider the following code snippet:

```
int main(void)
{
    // NB! The 2-nd byte in buffer is a canary
    const uint8_t buffer[] = {0xC0 | 0x1F, 0x80 | 0x3F};

    const uint8_t *begin = buffer;
    // NB! data size provided to get_utf8 function is 1 byte
    uint32_t result = get_utf8(&begin,  begin + 1);

    printf("buffer ptr: %p, begin ptr: %p, return value: %x\n",
        buffer, begin, result);

    return 0;
}
```

the actual output is:

> buffer ptr: 0x7ffd07e9d700, begin ptr: 0x7ffd07e9d702, return value: 7ff

the expected output is:

>buffer ptr: 0x7ffd07e9d700, begin ptr: 0x7ffd07e9d701, return value: ffffffff

Solution:
```
diff --git a/src/utf8_p.h b/src/utf8_p.h
index 577e540..ca43835 100644
--- a/src/utf8_p.h
+++ b/src/utf8_p.h
@@ -66,7 +66,7 @@ static inline uint32_t get_utf8(const uint8_t **buffer, const uint8_t *end)
         return ~0U;
     }
 
-    if (n < charsNeeded - 1)
+    if (n < charsNeeded)
         return ~0U;
 
     /* first continuation character */
```

Have a nice day!

**Comment by thiagomacieira** [comment]
Qt is also affected. Trying to figure out why I wrote that -1 in the first place.

**Comment by thiagomacieira** [comment]
Ah, I see what the problem is: the Qt code is slightly different from the TinyCBOR code. The `bytesAvailable` in Qt code accounts only for the continuation bytes, whereas in TinyCBOR it includes the first byte too.
