### ISSUE TITLE
cbor_encode_half_float() get error value

### ISSUE THREAD

**Issue by tianxiaoMCU** [intel/tinycbor#155]
Tested in QT 5.12
```
    float halfdata = 23.5;
    uint8_t buf[16] = {0};
    CborEncoder encoder;
    cbor_encoder_init(&encoder, &buf, sizeof(buf), 0);
    cbor_encode_half_float(&encoder, &halfdata);
```
run the demo,the encode data is **F9 00 00**

**Comment by thiagomacieira** [comment]
You've passed the pointer to a (full) float to `cbor_encode_half_float`. You're supposed to encode the data yourself, or by using `qfloat16`, `__fp16` or `cbor_encode_float_as_half_float` (see PR #149 for this function)
