### ISSUE TITLE
float comparison 

### ISSUE THREAD

**Issue by georgewu2007** [intel/tinycbor#160]
In cborpretty.c, there is an inaccurate floating point comparison.
On line 422: 
if (ival == fabs(val)) 

ival is an int64, but fabs returns a float. Testing for equality with two floats with the == operator will rarely return true. Instead you should take the difference of the two and compare that the value of the difference is greater the epsilon.

**Comment by thiagomacieira** [comment]
This in intentionally done, as we want to know if the number stored in the floating point is exactly that of the integral one. If it is, we'll use the integer-to-text conversion to get the full precision printed.

**Comment by georgewu2007** [comment]
couldn't you just have used float.is_integer. http://docs.python.org/2/library/stdtypes.html#float.is_integer

**Comment by erichkeane** [comment]
Isn't that a python function? Why would it be callable in a C app?

**Comment by thiagomacieira** [comment]
Exactly. There's no such function in the C standard library. The code you're looking at is implementing the same functionality.
