### ISSUE TITLE
When a new release ?

### ISSUE THREAD

**Issue by deiv** [intel/tinycbor#170]
There are some importants commits (like d072f461e995db64a9763b29a64f29c388b2a4e9)  needed for a working tinycbor.

When will publish it ?

**Comment by thiagomacieira** [comment]
I'll make a new 0.5 release.

**Comment by thiagomacieira** [comment]
https://github.com/intel/tinycbor/releases/tag/v0.5.3 created

**Comment by deiv** [comment]
Thanks !
