### ISSUE TITLE
Please tell me how to solve it

### ISSUE THREAD

**Issue by iotyib** [intel/tinycbor#183]
hello,I used tinycbor in keil and got an error. How can I solve this problem?
![image](https://user-images.githubusercontent.com/30848862/82201046-59aac600-9932-11ea-9eb3-c3c36f6a4531.png)

**Comment by C47D** [comment]
Check the 'compilersupport_p.h' file, I think tinycbor doesn't detect you are using a Keil compiler, that's why it tries to import a file Keil doesn't have and fails.

**Comment by thiagomacieira** [comment]
Please don't use images for what is essentially a text error message. Simply copy & paste the text.

That error comes as a fallback to other OSes and trying to figure out how to do `ntohs`. If your OS or library has such a way and TinyCBOR doesn't detect it, please submit a pull request with the fix.
