### ISSUE TITLE
[Question] Is it possible to dynamically add elements in between CBOR encoded data

### ISSUE THREAD

**Issue by dhrishi** [intel/tinycbor#185]
I want to CBOR encode this data: {"a": [1, 3], "b": [2, 4]} 

The thing is, I get the data 1, 2, 3, 4 in sequence from some other source. Using the TinyCBOR APIs, is it possible to create two independent CBOR encoded arrays:
=> [1], [2]
=> [1, 3], [2, 4]

and once they are complete, insert/append them together to get the entire CBOR encoded data for above? If yes, can you please provide a sample example?

**Comment by thiagomacieira** [comment]
Unfortunately, not with the current API. You need to buffer the data yourself in your own structures until the first array is complete, before you can emit "b".

What you're describing is a DOM (Document Object Model)-like API. I don't think TinyCBOR will extend to support that.

**Comment by dhrishi** [comment]
Okay. Thanks for the clarification.

**Comment by thiagomacieira** [comment]
What you can do is use two `CborEncoder` on two different buffers, so you can stream in parallel. Once you reach the end of your source, you re-stream the second buffer into the first. For that, the `cbor_encode_cbor` function requested in #162 would be very welcome. Without it, you need to transcode (decode and re-encode).
