### ISSUE TITLE
Undefined reference to 'static_assert'

### ISSUE THREAD

**Issue by Maltragor** [intel/tinycbor#189]
src/compilersupport_p.h 
```c
// ...
#ifndef assert
#  include <assert.h>
#endif

// ...
#if __STDC_VERSION__ >= 201112L || (defined(__cplusplus) && __cplusplus >= 201103L) || (defined(__cpp_static_assert) && __cpp_static_assert >= 200410)
#  define cbor_static_assert(x)         static_assert(x, #x)
#elif !defined(__cplusplus) && defined(__GNUC__) && (__GNUC__ * 100 + __GNUC_MINOR__ >= 406) && (__STDC_VERSION__ > 199901L)
#  define cbor_static_assert(x)         _Static_assert(x, #x)
// ...
```
I'm using mingw c compiler.

If you define your own assert(), assert.h is not included as expected.
But because  `__STDC_VERSION__ >= 201112L` is true, `cbor_static_assert()` is defined as `static_assert()`. But `static_assert()` would only be defined if `assert.h` is included.
The correct / working definition for `cbor_static_assert()` in this case would be the second one: `_Static_assert()`.

I don't know the conditions depending on c/c++/assert.h/compiler version/... . 
But if in c11 `static_assert()` is always a define and no compiler keyword, probably you could check if `defined(static_assert)` in addition to / as replacement for `__STDC_VERSION__  >= 201112L`. (If someone defines his own `static_assert()` probably it's no bad to use it independent of the compiler version)

(https://stackoverflow.com/questions/25552852/how-to-detect-if-a-compiler-supports-static-assert)

**Comment by thiagomacieira** [comment]
Compiler / C library bug. C11 requires that `<assert.h>` have the macro. Please report to MinGW and upgrade to the minimum version.

**Comment by thiagomacieira** [comment]
According to https://github.com/Alexpux/mingw-w64/commit/c7d4925fd55972ea5e71010888951db0fb35bdeb, this was added in 2012. Why are you using such an old version of MinGW?

**Comment by erichkeane** [comment]
>If you define your own assert(), assert.h is not included as expected.

Based on this line, I think he's hitting UB.  The #ifndef is preventing static_assert from being included from assert.h, since assert.h is never included.

That said, doing #define assert(...) is undefined behavior.  @Maltragor the C spec says that the word 'assert' is a reserved word, so you're not allowed to define it.

**Comment by thiagomacieira** [comment]
We're not doing `#define assert`. That's a `#define cbor_static_assert` and it's trying to figure out if it can use `static_assert` (C11, C++11), `_Static_assert` (C99 GCC >= 4.6) or poor man's static assertion. 

The problem is that we checked the macro for the C version and it said C11, but `static_assert` isn't defined. That means the C header `<assert.h>` failed to define it, in C11 mode, 9 years after the standard. GCC 5.1 and Clang 3.6 changed their C defaults to C11, but both are from 2015.

So this is likely MinGW with a GCC >= 5, but with a C library from before 2012. I'm not feeling forgiving. Fix the system.

**Comment by erichkeane** [comment]
Right, YOU'RE not, but @Maltragor is if I'm reading that correctly.  So he is doing:

    #define assert ....
    #include <tinycbor.h>

Am I right here?

**Comment by thiagomacieira** [comment]
That doesn't make sense either... This is `compilersupport_p.h` which is not a public header. This error can only happen when building TinyCBOR itself. So why would it already be defined, if not through a prior `#include <assert.h>` ?

**Comment by erichkeane** [comment]
Ah!  In that case, I'm not sure what he's saying then.  I took this: "If you define your own assert(), assert.h is not included as expected." to mean he defined his own assert.  I think we need more details :)

**Comment by Maltragor** [comment]
@erichkeane: Yes you are right.

I'm using tinycbor in a microcontroller program.
In addition to this, the application logic can be build on windows for better testing / debugging.

On the microcontroller I do not include assert.h but have my own assertion header / makros.
This allows me inserting a brekpoint command in the assert macro so the µC debugger stops at the assert() line in debug mode. In release mode my own assertion handler function is called to bring the system into a safe state, make some logging and then restart the controller. (And other behaviours based on several configurations)

And "of course" I made sure that my assertion header gets included inside tinycbor.

Since tinycbor only includes assert.h if assert() is not defined everything seemed to work as expected,... everything but static_assert. So the #ifdef assert seemed to be exactly for this use case^^

**Comment by erichkeane** [comment]
In that case, it appears that your custom 'assert' header doesn't properly implement the assert.h requirements, one of which is the static_assert macro. If you're going to be a library 'implementer', you have to implement to the standard.

Apparently, C11 defines static_assert thusly:
    
    #define static_assert _Static_assert 

So if you add that to your replacement 'assert.h' header, I believe you end up being alright.

**Comment by Maltragor** [comment]
Yes there are a several solutions.
The real problem, as has now been shown, was the misunderstanding of the `#ifndef assert` which was not to help to easily replace the assert macro by not including assert.h
Based on this initial expectation there seemed to be no reason why the conditions for the static_assert don't handle this accordingly.

Thank you @erichkeane, @thiagomacieira.
