### ISSUE TITLE
`CborValidateCompleteData` is ambiguous

### ISSUE THREAD

**Issue by liketechnik** [intel/tinycbor#225]
The `CborValidateCompleteData` flag for `cbor_value_validate()` does not specify if it verifies that the CBOR stream being parsed does not contain any data after the current element (passed as `it`) or after iteration over the whole stream / content of the current element for validation (done on a copy of the parser state / current element, cf. https://github.com/intel/tinycbor/blob/590c28a004c8de33d0885da39bbdf10b8c480d5b/src/cborvalidation.c#L646-L647).

---

In its current implementation, it does the former, i. e. initializing a parser on a non-empty CBOR stream and validating it with `CborValidateCompleteData` leads to a `CborErrorGarbageAtEnd`.

Since the description of `cbor_value_validate()` explicitly mentions using it *before* iterating over the stream ("the application can iterate over the items with certainty that no errors will appear during parsing"), I would have expected the latter behavior.

I have illustrated this with two very small sample programs in [a gist](https://gist.github.com/liketechnik/b8020bb8824de63e55f4b69e937e9154). 

---

In case there is agreement the current behavior is unexpected and should be changed, you can find the necessary change at https://github.com/liketechnik/tinycbor/commit/5c234647e45dd7eab9446fbbd00ed03de8ba98a4 (add `.patch` to the github url to directly access it as a patch: [5c23464.patch](https://github.com/liketechnik/tinycbor/commit/5c234647e45dd7eab9446fbbd00ed03de8ba98a4.patch)).

**Comment by thiagomacieira** [comment]
You're right, this is a bug.

**Comment by thiagomacieira** [comment]
Fixed as 9e97d078194f733d327ed5acb79fc50959e5abda, test added in e27261ed5e2ed059d160f16ae776951a08a861fc
