### ISSUE TITLE
Modifying data in cbor documents

### ISSUE THREAD

**Issue by inf265** [intel/tinycbor#228]
Hi all,
I have a question: How is it possible to modify one single value in a cbor document ? Do I have to parse everything and in-time re-encode it ?
Best Regards
Frédéric

**Comment by thiagomacieira** [comment]
Hello Frédéric

Yes, that's correct. TinyCBOR only has streaming support for parsing and encoding. You can't modify a document in memory through it -- depending on your modification, it may increase the size of the stream anyway,
