### ISSUE TITLE
Parser init with NULL return no error

### ISSUE THREAD

**Issue by noomio** [intel/tinycbor#233]
Hi,

Using 0.6.0

Should this return an error, currently both return CborNoError?

```
err = cbor_parser_init(NULL, 128, 0, &parser, &it);
err = cbor_value_validate_basic(&it);
```

**Comment by noomio** [comment]
Hi,

Yes, I'm on an embedded platform.

**Comment by thiagomacieira** [comment]
Then this is not a bug. You supplied the parser with a byte 0, which is expected to decode to an positive integer 0.
