### ISSUE TITLE
Question: how to get the data (bytes) of tag field ?

### ISSUE THREAD

**Issue by leonsal** [intel/tinycbor#257]
Hi,

My server is receiving request encoded in CBOR
sent from a JavaScript client. The request includes
Typed Arrays values (ex. Uint32Array).

I need to decode these arrays and convert their
data into an array of bytes.

In my decoder:
```
case CborTagType: {
    CborTag tag;
    cbor_value_get_tag(it, tag);
    // Checks for typed array tags from:
    // https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml
    if (tag < 64 || tag > 87) {
        return CborErrorUnknownTag;
   }
   // Get the typed array data as an array of bytes
   ?
}
```
Which function of the CBOR parser I can use to get the bytes of the received typed array ?

Regards.

**Comment by thiagomacieira** [comment]
First, once you've verified the tag, you advance to the next element (i.e,. `cbor_value_advance_fixed()`). Then you decode the tagged data.

According to the tags you've found, the array is transmitted as a byte string, not as a CBOR array. So you should NOT use `cbor_value_enter_container`. Instead, just use `cbor_value_copy_byte_string` or `cbor_value_dup_byte_string` to get the byte string data. If you want to attempt a zero-copy reading of that string, you can use `cbor_value_begin_string_iteration)` then while !`cbor_value_string_iteration_at_end()` do `cbor_value_get_byte_string_chunk()`.

Please note the tag is a mere suggestion. A tag of 66 or 70 may not be followed by a byte string - you need to verify that with `cbor_value_get_type()` after decoding the tag. There's also no guarantee that the byte string will have a size that is multiple of your expected element size.
