### ISSUE TITLE
README: linked documentation is 404

### ISSUE THREAD

**Issue by kfish** [intel/tinycbor#84]
The documentation link in the README:

    https://01org.github.io/tinycbor/current/

is not found (and github.com/01org/tinycbor no longer exists).

**Comment by erichkeane** [comment]
Looks like it moved here: https://intel.github.io/tinycbor/current/

**Comment by thiagomacieira** [comment]
Fixed by a2dab2c9b220a81489e0a4a38b11d53777bad38c
